-- MySQL Database version

CREATE TABLE BATCH_JOB_INSTANCE  (
  JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
  VERSION BIGINT ,
  JOB_NAME VARCHAR(100) NOT NULL,
  JOB_KEY VARCHAR(32) NOT NULL,
  constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
  JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
  VERSION BIGINT  ,
  JOB_INSTANCE_ID BIGINT NOT NULL,
  CREATE_TIME DATETIME NOT NULL,
  START_TIME DATETIME DEFAULT NULL ,
  END_TIME DATETIME DEFAULT NULL ,
  STATUS VARCHAR(10) ,
  EXIT_CODE VARCHAR(2500) ,
  EXIT_MESSAGE VARCHAR(2500) ,
  LAST_UPDATED DATETIME,
  JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL,
  PRIMARY KEY (JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
  JOB_EXECUTION_ID BIGINT NOT NULL ,
  KEY_NAME VARCHAR(100) NOT NULL ,
  TYPE_CD VARCHAR(6) ,
  STRING_VAL VARCHAR(250) ,
  DATE_VAL DATETIME DEFAULT NULL ,
  LONG_VAL BIGINT ,
  DOUBLE_VAL DOUBLE PRECISION ,
  IDENTIFYING CHAR(1) NOT NULL ,
  VERSION BIGINT ,
  FOREIGN KEY (JOB_EXECUTION_ID)
  REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
  STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY ,
  VERSION BIGINT NOT NULL,
  STEP_NAME VARCHAR(100) NOT NULL,
  JOB_EXECUTION_ID BIGINT NOT NULL,
  START_TIME DATETIME NOT NULL,
  END_TIME DATETIME DEFAULT NULL ,
  STATUS VARCHAR(10) ,
  COMMIT_COUNT BIGINT ,
  READ_COUNT BIGINT ,
  FILTER_COUNT BIGINT ,
  WRITE_COUNT BIGINT ,
  READ_SKIP_COUNT BIGINT ,
  WRITE_SKIP_COUNT BIGINT ,
  PROCESS_SKIP_COUNT BIGINT ,
  ROLLBACK_COUNT BIGINT ,
  EXIT_CODE VARCHAR(2500) ,
  EXIT_MESSAGE VARCHAR(2500) ,
  LAST_UPDATED DATETIME,
  FOREIGN KEY (JOB_EXECUTION_ID)
  REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
  STEP_EXECUTION_ID BIGINT PRIMARY KEY,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT TEXT ,
  FOREIGN KEY (STEP_EXECUTION_ID)
  REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
  JOB_EXECUTION_ID BIGINT PRIMARY KEY,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT TEXT ,
  FOREIGN KEY (JOB_EXECUTION_ID)
  REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT_SEQ (
  SEQ_NAME VARCHAR(60) NOT NULL,
  SEQ_KEY BIGINT NOT NULL,
  UNIQUE (SEQ_NAME)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT_SEQ (
  SEQ_NAME VARCHAR(60) NOT NULL,
  SEQ_KEY BIGINT NOT NULL,
  UNIQUE (SEQ_NAME)
) ;

CREATE TABLE BATCH_JOB_SEQ (
  SEQ_NAME VARCHAR(60) NOT NULL,
  SEQ_KEY BIGINT NOT NULL,
  UNIQUE (SEQ_NAME)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
  SEQ_NAME VARCHAR(60) NOT NULL,
  SEQ_KEY BIGINT NOT NULL,
  UNIQUE (SEQ_NAME)
) ;

INSERT INTO BATCH_JOB_EXECUTION_SEQ VALUES ('BATCH_JOB_EXECUTION', 0);
INSERT INTO BATCH_JOB_SEQ VALUES ('BATCH_JOB', 0);
INSERT INTO BATCH_STEP_EXECUTION_SEQ VALUES ('BATCH_STEP_EXECUTION', 0);
INSERT INTO BATCH_JOB_EXECUTION_CONTEXT_SEQ VALUES ('BATCH_JOB_EXECUTION_CONTEXT', 0);
INSERT INTO BATCH_STEP_EXECUTION_CONTEXT_SEQ VALUES ('BATCH_STEP_EXECUTION_CONTEXT', 0);